// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#import "TXSAccessTicket.h"
#include "access_ticket.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSAccessTicket;

namespace djinni_generated {

struct AccessTicket
{
    using CppType = ::textsort::AccessTicket;
    using ObjcType = TXSAccessTicket*;

    using Boxed = AccessTicket;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
