// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#import "TXSAccountInfo.h"


@implementation TXSAccountInfo

- (nonnull instancetype)initWithUserName:(nonnull NSString *)userName
                                password:(nonnull NSString *)password
{
    if (self = [super init]) {
        _userName = [userName copy];
        _password = [password copy];
    }
    return self;
}

+ (nonnull instancetype)accountInfoWithUserName:(nonnull NSString *)userName
                                       password:(nonnull NSString *)password
{
    return [(TXSAccountInfo*)[self alloc] initWithUserName:userName
                                                  password:password];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p userName:%@ password:%@>", self.class, (void *)self, self.userName, self.password];
}

@end
