// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#import "TXSReplyResult.h"
#include "reply_result.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSReplyResult;

namespace djinni_generated {

struct ReplyResult
{
    using CppType = ::textsort::ReplyResult;
    using ObjcType = TXSReplyResult*;

    using Boxed = ReplyResult;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
