// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#import "TXSTokenInfo+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto TokenInfo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.uuid),
            ::djinni::String::toCpp(obj.accessToken),
            ::djinni::String::toCpp(obj.refreshToken),
            ::djinni::I64::toCpp(obj.accessTokenExpire),
            ::djinni::I64::toCpp(obj.refreshTokenExpire)};
}

auto TokenInfo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TXSTokenInfo alloc] initWithUuid:(::djinni::String::fromCpp(cpp.uuid))
                                  accessToken:(::djinni::String::fromCpp(cpp.access_token))
                                 refreshToken:(::djinni::String::fromCpp(cpp.refresh_token))
                            accessTokenExpire:(::djinni::I64::fromCpp(cpp.access_token_expire))
                           refreshTokenExpire:(::djinni::I64::fromCpp(cpp.refresh_token_expire))];
}

}  // namespace djinni_generated
