// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#import "TXSReplyResult.h"
#import "TXSTokenInfo.h"
#import <Foundation/Foundation.h>


@protocol TXSVipuserListener

- (void)onCreateAccount:(nonnull TXSReplyResult *)result
                  token:(nonnull TXSTokenInfo *)token;

- (void)onLogin:(nonnull TXSReplyResult *)result
          token:(nonnull TXSTokenInfo *)token;

- (void)onReLogin:(nonnull TXSReplyResult *)result
            token:(nonnull TXSTokenInfo *)token;

- (void)onLogout:(nonnull TXSReplyResult *)result;

- (void)onDoBusiness:(nonnull TXSReplyResult *)result
            response:(nonnull NSData *)response;

@end
