// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#include "vipuser_service.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSVipuserService;

namespace djinni_generated {

class VipuserService
{
public:
    using CppType = std::shared_ptr<::textsort::VipuserService>;
    using CppOptType = std::shared_ptr<::textsort::VipuserService>;
    using ObjcType = TXSVipuserService*;

    using Boxed = VipuserService;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

