// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#import "TXSAccessTicket.h"
#import "TXSAccountInfo.h"
#import <Foundation/Foundation.h>
@class TXSVipuserService;
@protocol TXSVipuserListener;


@interface TXSVipuserService : NSObject

/** Instance Method  */
- (void)createAccount:(nonnull TXSAccountInfo *)account;

- (void)login:(nonnull TXSAccountInfo *)account;

- (void)reLogin:(nonnull TXSAccessTicket *)ticket;

- (void)logout:(nonnull TXSAccessTicket *)ticket;

- (void)doBusiness:(nonnull TXSAccessTicket *)ticket
           request:(nonnull NSData *)request;

/** Class Method */
+ (nullable TXSVipuserService *)createWithListener:(nullable id<TXSVipuserListener>)listener;

@end
