// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#import "TXSVipuserListener+Private.h"
#import "TXSVipuserListener.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "TXSReplyResult+Private.h"
#import "TXSTokenInfo+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class VipuserListener::ObjcProxy final
: public ::textsort::VipuserListener
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::VipuserListener;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void on_create_account(const ::textsort::ReplyResult & c_result, const ::textsort::TokenInfo & c_token) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onCreateAccount:(::djinni_generated::ReplyResult::fromCpp(c_result))
                                                                token:(::djinni_generated::TokenInfo::fromCpp(c_token))];
        }
    }
    void on_login(const ::textsort::ReplyResult & c_result, const ::textsort::TokenInfo & c_token) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onLogin:(::djinni_generated::ReplyResult::fromCpp(c_result))
                                                        token:(::djinni_generated::TokenInfo::fromCpp(c_token))];
        }
    }
    void on_re_login(const ::textsort::ReplyResult & c_result, const ::textsort::TokenInfo & c_token) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onReLogin:(::djinni_generated::ReplyResult::fromCpp(c_result))
                                                          token:(::djinni_generated::TokenInfo::fromCpp(c_token))];
        }
    }
    void on_logout(const ::textsort::ReplyResult & c_result) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onLogout:(::djinni_generated::ReplyResult::fromCpp(c_result))];
        }
    }
    void on_do_business(const ::textsort::ReplyResult & c_result, const std::vector<uint8_t> & c_response) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onDoBusiness:(::djinni_generated::ReplyResult::fromCpp(c_result))
                                                          response:(::djinni::Binary::fromCpp(c_response))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto VipuserListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto VipuserListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
