// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#include "vipuser_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol TXSVipuserListener;

namespace djinni_generated {

class VipuserListener
{
public:
    using CppType = std::shared_ptr<::textsort::VipuserListener>;
    using CppOptType = std::shared_ptr<::textsort::VipuserListener>;
    using ObjcType = id<TXSVipuserListener>;

    using Boxed = VipuserListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

