// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#pragma once

#include <string>
#include <utility>

namespace textsort {

struct AccessTicket final {
    std::string uuid;
    std::string access_token;

    AccessTicket(std::string uuid_,
                 std::string access_token_)
    : uuid(std::move(uuid_))
    , access_token(std::move(access_token_))
    {}
};

}  // namespace textsort
