// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#pragma once

#include <string>
#include <utility>

namespace textsort {

struct AccountInfo final {
    std::string user_name;
    std::string password;

    AccountInfo(std::string user_name_,
                std::string password_)
    : user_name(std::move(user_name_))
    , password(std::move(password_))
    {}
};

}  // namespace textsort
