// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#pragma once

#include <cstdint>
#include <vector>

namespace textsort {

struct ReplyResult;
struct TokenInfo;

class VipuserListener {
public:
    virtual ~VipuserListener() {}

    virtual void on_create_account(const ReplyResult & result, const TokenInfo & token) = 0;

    virtual void on_login(const ReplyResult & result, const TokenInfo & token) = 0;

    virtual void on_re_login(const ReplyResult & result, const TokenInfo & token) = 0;

    virtual void on_logout(const ReplyResult & result) = 0;

    virtual void on_do_business(const ReplyResult & result, const std::vector<uint8_t> & response) = 0;
};

}  // namespace textsort
