// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <vector>

namespace textsort {

class VipuserListener;
struct AccessTicket;
struct AccountInfo;

class VipuserService {
public:
    virtual ~VipuserService() {}

    /** Instance Method  */
    virtual void create_account(const AccountInfo & account) = 0;

    virtual void login(const AccountInfo & account) = 0;

    virtual void re_login(const AccessTicket & ticket) = 0;

    virtual void logout(const AccessTicket & ticket) = 0;

    virtual void do_business(const AccessTicket & ticket, const std::vector<uint8_t> & request) = 0;

    /** Class Method */
    static std::shared_ptr<VipuserService> create_with_listener(const std::shared_ptr<VipuserListener> & listener);
};

}  // namespace textsort
