// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vipuser.proto

#include "vipuser.pb.h"
#include "vipuser.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace vipuser {

static const char* Greeter_method_names[] = {
  "/vipuser.Greeter/CreateAcount",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_CreateAcount_(Greeter_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Greeter::Stub::CreateAcount(::grpc::ClientContext* context, const ::vipuser::VipUserRequest& request, ::vipuser::VipUserResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateAcount_, context, request, response);
}

void Greeter::Stub::experimental_async::CreateAcount(::grpc::ClientContext* context, const ::vipuser::VipUserRequest* request, ::vipuser::VipUserResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateAcount_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::CreateAcount(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vipuser::VipUserResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateAcount_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::CreateAcount(::grpc::ClientContext* context, const ::vipuser::VipUserRequest* request, ::vipuser::VipUserResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateAcount_, context, request, response, reactor);
}

void Greeter::Stub::experimental_async::CreateAcount(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vipuser::VipUserResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateAcount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vipuser::VipUserResponse>* Greeter::Stub::AsyncCreateAcountRaw(::grpc::ClientContext* context, const ::vipuser::VipUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vipuser::VipUserResponse>::Create(channel_.get(), cq, rpcmethod_CreateAcount_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vipuser::VipUserResponse>* Greeter::Stub::PrepareAsyncCreateAcountRaw(::grpc::ClientContext* context, const ::vipuser::VipUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vipuser::VipUserResponse>::Create(channel_.get(), cq, rpcmethod_CreateAcount_, context, request, false);
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::vipuser::VipUserRequest, ::vipuser::VipUserResponse>(
          [](Greeter::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vipuser::VipUserRequest* req,
             ::vipuser::VipUserResponse* resp) {
               return service->CreateAcount(ctx, req, resp);
             }, this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::CreateAcount(::grpc::ServerContext* context, const ::vipuser::VipUserRequest* request, ::vipuser::VipUserResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vipuser

