// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vipuser.proto

#include "vipuser.pb.h"
#include "vipuser.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace vipuser_proto {

static const char* VipUser_method_names[] = {
  "/vipuser_proto.VipUser/CreateAcount",
  "/vipuser_proto.VipUser/Login",
  "/vipuser_proto.VipUser/Logout",
  "/vipuser_proto.VipUser/ReLogin",
  "/vipuser_proto.VipUser/DoBusiness",
};

std::unique_ptr< VipUser::Stub> VipUser::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VipUser::Stub> stub(new VipUser::Stub(channel));
  return stub;
}

VipUser::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_CreateAcount_(VipUser_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Login_(VipUser_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Logout_(VipUser_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReLogin_(VipUser_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DoBusiness_(VipUser_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VipUser::Stub::CreateAcount(::grpc::ClientContext* context, const ::vipuser_proto::CreateAccountRequest& request, ::vipuser_proto::CreateAccountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateAcount_, context, request, response);
}

void VipUser::Stub::experimental_async::CreateAcount(::grpc::ClientContext* context, const ::vipuser_proto::CreateAccountRequest* request, ::vipuser_proto::CreateAccountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateAcount_, context, request, response, std::move(f));
}

void VipUser::Stub::experimental_async::CreateAcount(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vipuser_proto::CreateAccountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateAcount_, context, request, response, std::move(f));
}

void VipUser::Stub::experimental_async::CreateAcount(::grpc::ClientContext* context, const ::vipuser_proto::CreateAccountRequest* request, ::vipuser_proto::CreateAccountResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateAcount_, context, request, response, reactor);
}

void VipUser::Stub::experimental_async::CreateAcount(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vipuser_proto::CreateAccountResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateAcount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vipuser_proto::CreateAccountResponse>* VipUser::Stub::AsyncCreateAcountRaw(::grpc::ClientContext* context, const ::vipuser_proto::CreateAccountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vipuser_proto::CreateAccountResponse>::Create(channel_.get(), cq, rpcmethod_CreateAcount_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vipuser_proto::CreateAccountResponse>* VipUser::Stub::PrepareAsyncCreateAcountRaw(::grpc::ClientContext* context, const ::vipuser_proto::CreateAccountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vipuser_proto::CreateAccountResponse>::Create(channel_.get(), cq, rpcmethod_CreateAcount_, context, request, false);
}

::grpc::Status VipUser::Stub::Login(::grpc::ClientContext* context, const ::vipuser_proto::LoginRequest& request, ::vipuser_proto::LoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Login_, context, request, response);
}

void VipUser::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::vipuser_proto::LoginRequest* request, ::vipuser_proto::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void VipUser::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vipuser_proto::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void VipUser::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::vipuser_proto::LoginRequest* request, ::vipuser_proto::LoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

void VipUser::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vipuser_proto::LoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vipuser_proto::LoginResponse>* VipUser::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::vipuser_proto::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vipuser_proto::LoginResponse>::Create(channel_.get(), cq, rpcmethod_Login_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vipuser_proto::LoginResponse>* VipUser::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::vipuser_proto::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vipuser_proto::LoginResponse>::Create(channel_.get(), cq, rpcmethod_Login_, context, request, false);
}

::grpc::Status VipUser::Stub::Logout(::grpc::ClientContext* context, const ::vipuser_proto::LogoutRequest& request, ::vipuser_proto::LogoutResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Logout_, context, request, response);
}

void VipUser::Stub::experimental_async::Logout(::grpc::ClientContext* context, const ::vipuser_proto::LogoutRequest* request, ::vipuser_proto::LogoutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, std::move(f));
}

void VipUser::Stub::experimental_async::Logout(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vipuser_proto::LogoutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, std::move(f));
}

void VipUser::Stub::experimental_async::Logout(::grpc::ClientContext* context, const ::vipuser_proto::LogoutRequest* request, ::vipuser_proto::LogoutResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, reactor);
}

void VipUser::Stub::experimental_async::Logout(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vipuser_proto::LogoutResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vipuser_proto::LogoutResponse>* VipUser::Stub::AsyncLogoutRaw(::grpc::ClientContext* context, const ::vipuser_proto::LogoutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vipuser_proto::LogoutResponse>::Create(channel_.get(), cq, rpcmethod_Logout_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vipuser_proto::LogoutResponse>* VipUser::Stub::PrepareAsyncLogoutRaw(::grpc::ClientContext* context, const ::vipuser_proto::LogoutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vipuser_proto::LogoutResponse>::Create(channel_.get(), cq, rpcmethod_Logout_, context, request, false);
}

::grpc::Status VipUser::Stub::ReLogin(::grpc::ClientContext* context, const ::vipuser_proto::ReLoginRequest& request, ::vipuser_proto::ReLoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ReLogin_, context, request, response);
}

void VipUser::Stub::experimental_async::ReLogin(::grpc::ClientContext* context, const ::vipuser_proto::ReLoginRequest* request, ::vipuser_proto::ReLoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ReLogin_, context, request, response, std::move(f));
}

void VipUser::Stub::experimental_async::ReLogin(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vipuser_proto::ReLoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ReLogin_, context, request, response, std::move(f));
}

void VipUser::Stub::experimental_async::ReLogin(::grpc::ClientContext* context, const ::vipuser_proto::ReLoginRequest* request, ::vipuser_proto::ReLoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ReLogin_, context, request, response, reactor);
}

void VipUser::Stub::experimental_async::ReLogin(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vipuser_proto::ReLoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ReLogin_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vipuser_proto::ReLoginResponse>* VipUser::Stub::AsyncReLoginRaw(::grpc::ClientContext* context, const ::vipuser_proto::ReLoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vipuser_proto::ReLoginResponse>::Create(channel_.get(), cq, rpcmethod_ReLogin_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vipuser_proto::ReLoginResponse>* VipUser::Stub::PrepareAsyncReLoginRaw(::grpc::ClientContext* context, const ::vipuser_proto::ReLoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vipuser_proto::ReLoginResponse>::Create(channel_.get(), cq, rpcmethod_ReLogin_, context, request, false);
}

::grpc::Status VipUser::Stub::DoBusiness(::grpc::ClientContext* context, const ::vipuser_proto::BusinessRequest& request, ::vipuser_proto::BusinessResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DoBusiness_, context, request, response);
}

void VipUser::Stub::experimental_async::DoBusiness(::grpc::ClientContext* context, const ::vipuser_proto::BusinessRequest* request, ::vipuser_proto::BusinessResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DoBusiness_, context, request, response, std::move(f));
}

void VipUser::Stub::experimental_async::DoBusiness(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vipuser_proto::BusinessResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DoBusiness_, context, request, response, std::move(f));
}

void VipUser::Stub::experimental_async::DoBusiness(::grpc::ClientContext* context, const ::vipuser_proto::BusinessRequest* request, ::vipuser_proto::BusinessResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DoBusiness_, context, request, response, reactor);
}

void VipUser::Stub::experimental_async::DoBusiness(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vipuser_proto::BusinessResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DoBusiness_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vipuser_proto::BusinessResponse>* VipUser::Stub::AsyncDoBusinessRaw(::grpc::ClientContext* context, const ::vipuser_proto::BusinessRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vipuser_proto::BusinessResponse>::Create(channel_.get(), cq, rpcmethod_DoBusiness_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vipuser_proto::BusinessResponse>* VipUser::Stub::PrepareAsyncDoBusinessRaw(::grpc::ClientContext* context, const ::vipuser_proto::BusinessRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vipuser_proto::BusinessResponse>::Create(channel_.get(), cq, rpcmethod_DoBusiness_, context, request, false);
}

VipUser::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VipUser_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VipUser::Service, ::vipuser_proto::CreateAccountRequest, ::vipuser_proto::CreateAccountResponse>(
          [](VipUser::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vipuser_proto::CreateAccountRequest* req,
             ::vipuser_proto::CreateAccountResponse* resp) {
               return service->CreateAcount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VipUser_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VipUser::Service, ::vipuser_proto::LoginRequest, ::vipuser_proto::LoginResponse>(
          [](VipUser::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vipuser_proto::LoginRequest* req,
             ::vipuser_proto::LoginResponse* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VipUser_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VipUser::Service, ::vipuser_proto::LogoutRequest, ::vipuser_proto::LogoutResponse>(
          [](VipUser::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vipuser_proto::LogoutRequest* req,
             ::vipuser_proto::LogoutResponse* resp) {
               return service->Logout(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VipUser_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VipUser::Service, ::vipuser_proto::ReLoginRequest, ::vipuser_proto::ReLoginResponse>(
          [](VipUser::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vipuser_proto::ReLoginRequest* req,
             ::vipuser_proto::ReLoginResponse* resp) {
               return service->ReLogin(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VipUser_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VipUser::Service, ::vipuser_proto::BusinessRequest, ::vipuser_proto::BusinessResponse>(
          [](VipUser::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vipuser_proto::BusinessRequest* req,
             ::vipuser_proto::BusinessResponse* resp) {
               return service->DoBusiness(ctx, req, resp);
             }, this)));
}

VipUser::Service::~Service() {
}

::grpc::Status VipUser::Service::CreateAcount(::grpc::ServerContext* context, const ::vipuser_proto::CreateAccountRequest* request, ::vipuser_proto::CreateAccountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VipUser::Service::Login(::grpc::ServerContext* context, const ::vipuser_proto::LoginRequest* request, ::vipuser_proto::LoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VipUser::Service::Logout(::grpc::ServerContext* context, const ::vipuser_proto::LogoutRequest* request, ::vipuser_proto::LogoutResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VipUser::Service::ReLogin(::grpc::ServerContext* context, const ::vipuser_proto::ReLoginRequest* request, ::vipuser_proto::ReLoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VipUser::Service::DoBusiness(::grpc::ServerContext* context, const ::vipuser_proto::BusinessRequest* request, ::vipuser_proto::BusinessResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vipuser_proto

