// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

package per.elwin.vipuser.djinni;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ final class AccountInfo {


    /*package*/ final String mUserName;

    /*package*/ final String mPassword;

    public AccountInfo(
            @Nonnull String userName,
            @Nonnull String password) {
        this.mUserName = userName;
        this.mPassword = password;
    }

    @Nonnull
    public String getUserName() {
        return mUserName;
    }

    @Nonnull
    public String getPassword() {
        return mPassword;
    }

    @Override
    public String toString() {
        return "AccountInfo{" +
                "mUserName=" + mUserName +
                "," + "mPassword=" + mPassword +
        "}";
    }

}
