// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

package per.elwin.vipuser.djinni;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ final class ReplyResult {


    /*package*/ final int mCode;

    /*package*/ final String mMessage;

    public ReplyResult(
            int code,
            @Nonnull String message) {
        this.mCode = code;
        this.mMessage = message;
    }

    public int getCode() {
        return mCode;
    }

    @Nonnull
    public String getMessage() {
        return mMessage;
    }

    @Override
    public String toString() {
        return "ReplyResult{" +
                "mCode=" + mCode +
                "," + "mMessage=" + mMessage +
        "}";
    }

}
