// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

package per.elwin.vipuser.djinni;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ final class TokenInfo {


    /*package*/ final String mUuid;

    /*package*/ final String mAccessToken;

    /*package*/ final String mRefreshToken;

    /*package*/ final long mAccessTokenExpire;

    /*package*/ final long mRefreshTokenExpire;

    public TokenInfo(
            @Nonnull String uuid,
            @Nonnull String accessToken,
            @Nonnull String refreshToken,
            long accessTokenExpire,
            long refreshTokenExpire) {
        this.mUuid = uuid;
        this.mAccessToken = accessToken;
        this.mRefreshToken = refreshToken;
        this.mAccessTokenExpire = accessTokenExpire;
        this.mRefreshTokenExpire = refreshTokenExpire;
    }

    @Nonnull
    public String getUuid() {
        return mUuid;
    }

    @Nonnull
    public String getAccessToken() {
        return mAccessToken;
    }

    @Nonnull
    public String getRefreshToken() {
        return mRefreshToken;
    }

    public long getAccessTokenExpire() {
        return mAccessTokenExpire;
    }

    public long getRefreshTokenExpire() {
        return mRefreshTokenExpire;
    }

    @Override
    public String toString() {
        return "TokenInfo{" +
                "mUuid=" + mUuid +
                "," + "mAccessToken=" + mAccessToken +
                "," + "mRefreshToken=" + mRefreshToken +
                "," + "mAccessTokenExpire=" + mAccessTokenExpire +
                "," + "mRefreshTokenExpire=" + mRefreshTokenExpire +
        "}";
    }

}
