// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

package per.elwin.vipuser.djinni;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ interface VipuserListener {
    public void onCreateAccount(@Nonnull ReplyResult result, @Nonnull TokenInfo token);

    public void onLogin(@Nonnull ReplyResult result, @Nonnull TokenInfo token);

    public void onReLogin(@Nonnull ReplyResult result, @Nonnull TokenInfo token);

    public void onLogout(@Nonnull ReplyResult result);

    public void onDoBusiness(@Nonnull ReplyResult result, @Nonnull byte[] response);
}
