// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#pragma once

#include "djinni_support.hpp"
#include "vipuser_listener.hpp"

namespace djinni_generated {

class NativeVipuserListener final : ::djinni::JniInterface<::textsort::VipuserListener, NativeVipuserListener> {
public:
    using CppType = std::shared_ptr<::textsort::VipuserListener>;
    using CppOptType = std::shared_ptr<::textsort::VipuserListener>;
    using JniType = jobject;

    using Boxed = NativeVipuserListener;

    ~NativeVipuserListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeVipuserListener>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeVipuserListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeVipuserListener();
    friend ::djinni::JniClass<NativeVipuserListener>;
    friend ::djinni::JniInterface<::textsort::VipuserListener, NativeVipuserListener>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::textsort::VipuserListener
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void on_create_account(const ::textsort::ReplyResult & result, const ::textsort::TokenInfo & token) override;
        void on_login(const ::textsort::ReplyResult & result, const ::textsort::TokenInfo & token) override;
        void on_re_login(const ::textsort::ReplyResult & result, const ::textsort::TokenInfo & token) override;
        void on_logout(const ::textsort::ReplyResult & result) override;
        void on_do_business(const ::textsort::ReplyResult & result, const std::vector<uint8_t> & response) override;

    private:
        friend ::djinni::JniInterface<::textsort::VipuserListener, ::djinni_generated::NativeVipuserListener>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("per/elwin/vipuser/djinni/VipuserListener") };
    const jmethodID method_onCreateAccount { ::djinni::jniGetMethodID(clazz.get(), "onCreateAccount", "(Lper/elwin/vipuser/djinni/ReplyResult;Lper/elwin/vipuser/djinni/TokenInfo;)V") };
    const jmethodID method_onLogin { ::djinni::jniGetMethodID(clazz.get(), "onLogin", "(Lper/elwin/vipuser/djinni/ReplyResult;Lper/elwin/vipuser/djinni/TokenInfo;)V") };
    const jmethodID method_onReLogin { ::djinni::jniGetMethodID(clazz.get(), "onReLogin", "(Lper/elwin/vipuser/djinni/ReplyResult;Lper/elwin/vipuser/djinni/TokenInfo;)V") };
    const jmethodID method_onLogout { ::djinni::jniGetMethodID(clazz.get(), "onLogout", "(Lper/elwin/vipuser/djinni/ReplyResult;)V") };
    const jmethodID method_onDoBusiness { ::djinni::jniGetMethodID(clazz.get(), "onDoBusiness", "(Lper/elwin/vipuser/djinni/ReplyResult;[B)V") };
};

}  // namespace djinni_generated
