// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#pragma once

#include "djinni_support.hpp"
#include "vipuser_service.hpp"

namespace djinni_generated {

class NativeVipuserService final : ::djinni::JniInterface<::textsort::VipuserService, NativeVipuserService> {
public:
    using CppType = std::shared_ptr<::textsort::VipuserService>;
    using CppOptType = std::shared_ptr<::textsort::VipuserService>;
    using JniType = jobject;

    using Boxed = NativeVipuserService;

    ~NativeVipuserService();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeVipuserService>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeVipuserService>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeVipuserService();
    friend ::djinni::JniClass<NativeVipuserService>;
    friend ::djinni::JniInterface<::textsort::VipuserService, NativeVipuserService>;

};

}  // namespace djinni_generated
