// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#include "NativeVipuserListener.hpp"  // my header
#include "Marshal.hpp"
#include "NativeReplyResult.hpp"
#include "NativeTokenInfo.hpp"

namespace djinni_generated {

NativeVipuserListener::NativeVipuserListener() : ::djinni::JniInterface<::textsort::VipuserListener, NativeVipuserListener>() {}

NativeVipuserListener::~NativeVipuserListener() = default;

NativeVipuserListener::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeVipuserListener::JavaProxy::~JavaProxy() = default;

void NativeVipuserListener::JavaProxy::on_create_account(const ::textsort::ReplyResult & c_result, const ::textsort::TokenInfo & c_token) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVipuserListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onCreateAccount,
                           ::djinni::get(::djinni_generated::NativeReplyResult::fromCpp(jniEnv, c_result)),
                           ::djinni::get(::djinni_generated::NativeTokenInfo::fromCpp(jniEnv, c_token)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeVipuserListener::JavaProxy::on_login(const ::textsort::ReplyResult & c_result, const ::textsort::TokenInfo & c_token) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVipuserListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onLogin,
                           ::djinni::get(::djinni_generated::NativeReplyResult::fromCpp(jniEnv, c_result)),
                           ::djinni::get(::djinni_generated::NativeTokenInfo::fromCpp(jniEnv, c_token)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeVipuserListener::JavaProxy::on_re_login(const ::textsort::ReplyResult & c_result, const ::textsort::TokenInfo & c_token) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVipuserListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onReLogin,
                           ::djinni::get(::djinni_generated::NativeReplyResult::fromCpp(jniEnv, c_result)),
                           ::djinni::get(::djinni_generated::NativeTokenInfo::fromCpp(jniEnv, c_token)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeVipuserListener::JavaProxy::on_logout(const ::textsort::ReplyResult & c_result) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVipuserListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onLogout,
                           ::djinni::get(::djinni_generated::NativeReplyResult::fromCpp(jniEnv, c_result)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeVipuserListener::JavaProxy::on_do_business(const ::textsort::ReplyResult & c_result, const std::vector<uint8_t> & c_response) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVipuserListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onDoBusiness,
                           ::djinni::get(::djinni_generated::NativeReplyResult::fromCpp(jniEnv, c_result)),
                           ::djinni::get(::djinni::Binary::fromCpp(jniEnv, c_response)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
