// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from vipuser.djinni

#include "NativeAccessTicket.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeAccessTicket::NativeAccessTicket() = default;

NativeAccessTicket::~NativeAccessTicket() = default;

auto NativeAccessTicket::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeAccessTicket>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.uuid)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.access_token)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeAccessTicket::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeAccessTicket>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mUuid)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mAccessToken))};
}

}  // namespace djinni_generated
